"""Shared run-state for the AI Film Pipeline (spec §6.7).

A thin async Redis layer that the scheduler daemon, worker fleet, and compositor
all read/write so a run has one coherent view. Mirrors ``libs/storage``: the
implementation lives in :mod:`state.store`; this package re-exports its API.
"""

from state.store import (
    PHASE_BLOCKED,
    PHASE_COMPLETE,
    PHASE_COMPOSITING,
    PHASE_EXECUTING,
    PHASE_PAUSED,
    PLAN_QUEUED,
    PLAN_RUNNING,
    PLAN_SUCCEEDED,
    PLAN_FAILED,
    PLAN_JOB_TTL_S,
    UserExistsError,
    approve_package,
    create_plan_job,
    create_user,
    get_cost,
    get_plan_job,
    get_plan_job_owner,
    get_dep_provider_urls,
    get_final_url,
    get_node,
    get_package,
    get_project_owner,
    get_project_phase,
    get_user_by_id,
    get_user_by_username,
    set_user_password_hash,
    increment_attempts,
    iter_all_packages,
    iter_approved_packages,
    iter_user_packages,
    save_package,
    set_final_url,
    set_node_status,
    set_plan_failed,
    set_plan_stage,
    set_plan_succeeded,
    set_project_phase,
    use_client,
)

__all__ = [
    "PHASE_EXECUTING",
    "PHASE_COMPOSITING",
    "PHASE_COMPLETE",
    "PHASE_BLOCKED",
    "PHASE_PAUSED",
    "PLAN_QUEUED",
    "PLAN_RUNNING",
    "PLAN_SUCCEEDED",
    "PLAN_FAILED",
    "PLAN_JOB_TTL_S",
    "create_plan_job",
    "set_plan_stage",
    "set_plan_succeeded",
    "set_plan_failed",
    "get_plan_job",
    "get_plan_job_owner",
    "use_client",
    "save_package",
    "get_package",
    "approve_package",
    "iter_approved_packages",
    "iter_all_packages",
    "iter_user_packages",
    "get_project_owner",
    "create_user",
    "get_user_by_username",
    "get_user_by_id",
    "set_user_password_hash",
    "UserExistsError",
    "set_node_status",
    "get_node",
    "increment_attempts",
    "get_dep_provider_urls",
    "get_project_phase",
    "set_project_phase",
    "set_final_url",
    "get_final_url",
    "get_cost",
]
